### ISSUE TITLE
disable old project in Visual Studio Marketplace

### ISSUE THREAD

**Issue by alanlivio** [likern/vscode-workspace-explorer#11]
There are two projects in  Visual Studio  Marketplace:
https://marketplace.visualstudio.com/items?itemName=tomsaunders.vscode-workspace-explorer
https://marketplace.visualstudio.com/items?itemName=tomsaunders-code.workspace-explorer
I suggest only remain the last for avoid confusion.

**Comment by likern** [comment]
This project is not from original author. I copied it from GitLab, but actually didn't do anything useful.

This project was never been published in marketplace.

**Comment by likern** [comment]
Please, contact original project.

**Comment by alanlivio** [comment]
Thank you. Sorry for the confusion.
